---
- name: Update Packages
  hosts: all
  gather_facts: yes
  become: yes
  tasks: 
    - name: Update Packages on webserver (CentOS8)
      when: ansible_facts["pkg_mgr"] ==  "dnf"
      dnf:
        name: "*"
        state: latest

    - name: Update Packages on database (Ubuntu)
      when: ansible_facts["pkg_mgr"] == "apt"
      apt:
        name: "*"
        state: fixed

    - name: Install vim, curl, wget, git
      when: ansible_facts["pkg_mgr"] ==  "dnf"
      dnf:
        name: 
          - vim
          - curl
          - wget
          - git
        state: latest