---
- name: Setup WordPress
  hosts: webserver
  gather_facts: true
  become: yes
  tasks:
    - name: Install and Start Apache
      dnf:
        name: httpd
        state: latest
    
    - name: Start Apache
      systemd:
        name: httpd
        state: started
        enabled: yes
    